travis:
  secure:
    BINSTAR_TOKEN: me4WffLooLKKMW5tl27MOvkYJu3PIV4r/FsCCR6PLD+67j1QYGbKygCsXXl28/Bq0gP++gSFdAQoRLLj2khuIyvPxvAxA7+KJDHHqyVLGAMMCqCb7UJl7GL1s6/IUR92V5MmTiAshCBRn//BSYR68yZA9B7GbywOV5DqAWTyTJ6jhRMXlxSCzyfceqLxuEp1N5n5aUUI1jrBK6ylfOn0rU4PpA0DtBf+un29Tzv2swjuLK3uoLsZ5eokR+qnlxpRRg7ySNTvhzRmRGZvGcG2NYZLcjXlIRxJ21uSiMTlItOaax7jI8YL4X8jJZA6GlEsAY0s0mpsVcqKnlnOhs55MYaNj9tWAJN0qEXyNOlBz5HiGJhF0K/mK/dlojbVJp70gzsI4hMqAZdIYzhVNsFXy615nQcYBFeWfaGF7wL1uXUTzYY4Fh28s/waC8f6p5Bii/eaQU6rsWjx4sZlSOzllb9rm7hZocHB5KNvkuLWqSZCeVJpUZSN/8v5cw+gq7IA2xTzE2ZrLwojflTZRjoBYV6D1R+ISUa5wm+WLnilWzZn4cduGvF89TQZBLlqc5P+KRHF84lNIqdDIWSLgDP7JqNzhPZ4iiKdwpSzjoquw5Q06bmwpZ0ksbnOmiuo2+8i7zDFYshFbCtzSWlWi4ZkbuFSC1n4ZTta7dPAOXKPwxQ=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
