travis:
  secure:
    BINSTAR_TOKEN: KKNyGI7uVXufsrv5qMe8atJ3wspo+sMfm/vouy3X6TFuWNdMNcGVcDfcQQ43jFMklpok/573PGR1xSEXTR9iyVUg7KiT6caSRIqkR+O/U9MUVZ70mHmuWYCr96wxp4rllo6AV1G5a91nA2l06b8fcZGEszTrxWe/t8KWNoSvgL/trbOwDCpcKutMDF09AQsWJqAU/C6ldSeEElmYYWoCp42xveK3U/sYxbiH+OnSUTQs9Nywu1rykbnr5d+zUYufB66+xCdUZy0ssiSG6NKOy9iGkyNq6N5OqbZDbZSFnmXZ6AtkN8CEVDWXkBZ0/xe3M/wfiCEYp17DLITVPQS7yrjACr46BsEEl5Xifc8YNppaZ/za3ayPnr2Aj9aHHZ00otu6Yx+nHbp5++ZiDRtakRQSP9ruJJiioZ8B/ipJJe3SNN6DuPGvnbwejG0fggR+sNTU9TfyyNkJKivhBTsNYBwjq636ZzRo/sdtXuDTwe3xTuy250Zyv0IzKmgMyB6PfxSiKeqUrb8W8FMglnJKJdCpuhjEofDKoI8kmdBYkTZROnRIjTb+xyQnnEQ22Kt/Vfc0xQKeT0fSls1YOTIhmvS6w4TUbX/ziE5J+ILCUML2nkgtIDApxWsfQ3tlCrR9NdRMNyHFRKL2QL/YDvp0tIKB4G0TjOsPUmuoCitmK4k=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
